/**
 * Contract ABIs for SylOS Civilization Contracts
 *
 * Minimal ABIs containing only the functions used by the frontend.
 * Full ABIs are generated by Hardhat compilation in smart-contracts/artifacts/.
 */

// ─── AgentRegistry ────────────────────────────────────────────

export const AGENT_REGISTRY_ABI = [
  // Read
  { inputs: [{ name: '_agentId', type: 'bytes32' }], name: 'getAgent', outputs: [{ components: [{ name: 'agentId', type: 'bytes32' }, { name: 'sponsor', type: 'address' }, { name: 'name', type: 'string' }, { name: 'role', type: 'uint8' }, { name: 'stakeBond', type: 'uint256' }, { name: 'slashedAmount', type: 'uint256' }, { name: 'permissionHash', type: 'bytes32' }, { name: 'status', type: 'uint8' }, { name: 'spawnedAt', type: 'uint256' }, { name: 'expiresAt', type: 'uint256' }, { name: 'reputationScore', type: 'uint256' }, { name: 'sessionWallet', type: 'address' }, { name: 'totalActions', type: 'uint256' }, { name: 'lastActiveAt', type: 'uint256' }, { name: 'identityCID', type: 'string' }], name: '', type: 'tuple' }], stateMutability: 'view', type: 'function' },
  { inputs: [{ name: '_agentId', type: 'bytes32' }], name: 'isActive', outputs: [{ type: 'bool' }], stateMutability: 'view', type: 'function' },
  { inputs: [{ name: '_sponsor', type: 'address' }], name: 'getSponsorAgents', outputs: [{ type: 'bytes32[]' }], stateMutability: 'view', type: 'function' },
  { inputs: [{ name: '_sponsor', type: 'address' }], name: 'getSponsorActiveCount', outputs: [{ type: 'uint256' }], stateMutability: 'view', type: 'function' },
  { inputs: [], name: 'getTotalAgents', outputs: [{ type: 'uint256' }], stateMutability: 'view', type: 'function' },
  { inputs: [{ name: '_agentId', type: 'bytes32' }], name: 'getReputationTier', outputs: [{ type: 'string' }], stateMutability: 'view', type: 'function' },
  { inputs: [{ name: '_agentId', type: 'bytes32' }], name: 'getIdentityCID', outputs: [{ type: 'string' }], stateMutability: 'view', type: 'function' },
  // Write — Identity
  { inputs: [{ name: '_agentId', type: 'bytes32' }, { name: '_identityCID', type: 'string' }], name: 'updateIdentity', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  { inputs: [], name: 'minStakeBond', outputs: [{ type: 'uint256' }], stateMutability: 'view', type: 'function' },
  { inputs: [], name: 'maxAgentsPerSponsor', outputs: [{ type: 'uint256' }], stateMutability: 'view', type: 'function' },
  // Write
  { inputs: [{ name: '_name', type: 'string' }, { name: '_role', type: 'uint8' }, { name: '_stakeBond', type: 'uint256' }, { name: '_permissionHash', type: 'bytes32' }, { name: '_expiresAt', type: 'uint256' }, { name: '_sessionWallet', type: 'address' }], name: 'spawnAgent', outputs: [{ type: 'bytes32' }], stateMutability: 'nonpayable', type: 'function' },
  { inputs: [{ name: '_agentId', type: 'bytes32' }], name: 'pauseAgent', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  { inputs: [{ name: '_agentId', type: 'bytes32' }], name: 'resumeAgent', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  { inputs: [{ name: '_agentId', type: 'bytes32' }], name: 'revokeAgent', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  { inputs: [{ name: '_agentId', type: 'bytes32' }, { name: '_newExpiry', type: 'uint256' }], name: 'renewAgent', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  { inputs: [{ name: '_agentId', type: 'bytes32' }, { name: '_amount', type: 'uint256' }], name: 'topUpStake', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  // Events
  { anonymous: false, inputs: [{ indexed: true, name: 'agentId', type: 'bytes32' }, { indexed: true, name: 'sponsor', type: 'address' }, { indexed: false, name: 'name', type: 'string' }, { indexed: false, name: 'role', type: 'uint8' }, { indexed: false, name: 'stakeBond', type: 'uint256' }, { indexed: false, name: 'expiresAt', type: 'uint256' }, { indexed: false, name: 'sessionWallet', type: 'address' }], name: 'AgentSpawned', type: 'event' },
  { anonymous: false, inputs: [{ indexed: true, name: 'agentId', type: 'bytes32' }, { indexed: true, name: 'by', type: 'address' }], name: 'AgentPaused', type: 'event' },
  { anonymous: false, inputs: [{ indexed: true, name: 'agentId', type: 'bytes32' }, { indexed: true, name: 'by', type: 'address' }], name: 'AgentResumed', type: 'event' },
  { anonymous: false, inputs: [{ indexed: true, name: 'agentId', type: 'bytes32' }, { indexed: true, name: 'by', type: 'address' }, { indexed: false, name: 'stakeReturned', type: 'uint256' }], name: 'AgentRevoked', type: 'event' },
  { anonymous: false, inputs: [{ indexed: true, name: 'agentId', type: 'bytes32' }, { indexed: false, name: 'amount', type: 'uint256' }], name: 'AgentSlashed', type: 'event' },
  { anonymous: false, inputs: [{ indexed: true, name: 'agentId', type: 'bytes32' }, { indexed: false, name: 'newScore', type: 'uint256' }], name: 'AgentReputationUpdated', type: 'event' },
  { anonymous: false, inputs: [{ indexed: true, name: 'agentId', type: 'bytes32' }, { indexed: false, name: 'identityCID', type: 'string' }], name: 'AgentIdentityUpdated', type: 'event' },
] as const

// ─── ReputationScore ──────────────────────────────────────────

export const REPUTATION_SCORE_ABI = [
  // Read
  { inputs: [{ name: '_agentId', type: 'bytes32' }], name: 'getReputation', outputs: [{ type: 'uint256' }], stateMutability: 'view', type: 'function' },
  { inputs: [{ name: '_agentId', type: 'bytes32' }], name: 'getReputationRecord', outputs: [{ components: [{ name: 'score', type: 'uint256' }, { name: 'totalPositive', type: 'uint256' }, { name: 'totalNegative', type: 'uint256' }, { name: 'lastUpdatedAt', type: 'uint256' }, { name: 'lastDecayAt', type: 'uint256' }], name: '', type: 'tuple' }], stateMutability: 'view', type: 'function' },
  { inputs: [{ name: '_agentId', type: 'bytes32' }], name: 'getTier', outputs: [{ type: 'uint8' }], stateMutability: 'view', type: 'function' },
  { inputs: [{ name: '_agentId', type: 'bytes32' }], name: 'getActionHistory', outputs: [{ components: [{ name: 'agentId', type: 'bytes32' }, { name: 'actionType', type: 'uint8' }, { name: 'delta', type: 'int256' }, { name: 'scoreBefore', type: 'uint256' }, { name: 'scoreAfter', type: 'uint256' }, { name: 'reason', type: 'string' }, { name: 'timestamp', type: 'uint256' }], name: '', type: 'tuple[]' }], stateMutability: 'view', type: 'function' },
  { inputs: [{ name: '_agentId', type: 'bytes32' }], name: 'getActionHistoryLength', outputs: [{ type: 'uint256' }], stateMutability: 'view', type: 'function' },
  // Events
  { anonymous: false, inputs: [{ indexed: true, name: 'agentId', type: 'bytes32' }, { indexed: false, name: 'actionType', type: 'uint8' }, { indexed: false, name: 'delta', type: 'int256' }, { indexed: false, name: 'newScore', type: 'uint256' }, { indexed: false, name: 'reason', type: 'string' }], name: 'ReputationUpdated', type: 'event' },
  { anonymous: false, inputs: [{ indexed: true, name: 'agentId', type: 'bytes32' }, { indexed: false, name: 'decayAmount', type: 'uint256' }, { indexed: false, name: 'newScore', type: 'uint256' }], name: 'DecayApplied', type: 'event' },
] as const

// ─── SlashingEngine ───────────────────────────────────────────

export const SLASHING_ENGINE_ABI = [
  // Read
  { inputs: [{ name: '_recordId', type: 'uint256' }], name: 'getSlashRecord', outputs: [{ components: [{ name: 'agentId', type: 'bytes32' }, { name: 'violationType', type: 'uint8' }, { name: 'slashAmount', type: 'uint256' }, { name: 'reputationPenalty', type: 'uint256' }, { name: 'evidence', type: 'string' }, { name: 'reporter', type: 'address' }, { name: 'timestamp', type: 'uint256' }, { name: 'executed', type: 'bool' }], name: '', type: 'tuple' }], stateMutability: 'view', type: 'function' },
  { inputs: [{ name: '_agentId', type: 'bytes32' }], name: 'getAgentSlashRecords', outputs: [{ type: 'uint256[]' }], stateMutability: 'view', type: 'function' },
  { inputs: [{ name: '_agentId', type: 'bytes32' }], name: 'getAgentSlashCount', outputs: [{ type: 'uint256' }], stateMutability: 'view', type: 'function' },
  { inputs: [], name: 'getTotalRecords', outputs: [{ type: 'uint256' }], stateMutability: 'view', type: 'function' },
  { inputs: [], name: 'totalSlashed', outputs: [{ type: 'uint256' }], stateMutability: 'view', type: 'function' },
  { inputs: [], name: 'totalViolations', outputs: [{ type: 'uint256' }], stateMutability: 'view', type: 'function' },
  // Events
  { anonymous: false, inputs: [{ indexed: true, name: 'recordId', type: 'uint256' }, { indexed: true, name: 'agentId', type: 'bytes32' }, { indexed: false, name: 'violationType', type: 'uint8' }, { indexed: false, name: 'reporter', type: 'address' }, { indexed: false, name: 'evidence', type: 'string' }], name: 'ViolationReported', type: 'event' },
  { anonymous: false, inputs: [{ indexed: true, name: 'recordId', type: 'uint256' }, { indexed: true, name: 'agentId', type: 'bytes32' }, { indexed: false, name: 'slashAmount', type: 'uint256' }, { indexed: false, name: 'reputationDelta', type: 'int256' }, { indexed: false, name: 'autoRevoked', type: 'bool' }], name: 'SlashExecuted', type: 'event' },
] as const

// ─── PaymentStreaming ─────────────────────────────────────────

export const PAYMENT_STREAMING_ABI = [
  // Read
  { inputs: [{ name: '_streamId', type: 'uint256' }], name: 'getStream', outputs: [{ components: [{ name: 'streamId', type: 'uint256' }, { name: 'sponsor', type: 'address' }, { name: 'agent', type: 'address' }, { name: 'agentId', type: 'bytes32' }, { name: 'token', type: 'address' }, { name: 'deposit', type: 'uint256' }, { name: 'ratePerSecond', type: 'uint256' }, { name: 'withdrawn', type: 'uint256' }, { name: 'startTime', type: 'uint256' }, { name: 'pausedAt', type: 'uint256' }, { name: 'pausedDuration', type: 'uint256' }, { name: 'active', type: 'bool' }, { name: 'canceled', type: 'bool' }], name: '', type: 'tuple' }], stateMutability: 'view', type: 'function' },
  { inputs: [{ name: '_streamId', type: 'uint256' }], name: 'getEarned', outputs: [{ type: 'uint256' }], stateMutability: 'view', type: 'function' },
  { inputs: [{ name: '_streamId', type: 'uint256' }], name: 'getWithdrawable', outputs: [{ type: 'uint256' }], stateMutability: 'view', type: 'function' },
  { inputs: [{ name: '_streamId', type: 'uint256' }], name: 'getTimeRemaining', outputs: [{ type: 'uint256' }], stateMutability: 'view', type: 'function' },
  { inputs: [{ name: '_sponsor', type: 'address' }], name: 'getSponsorStreams', outputs: [{ type: 'uint256[]' }], stateMutability: 'view', type: 'function' },
  { inputs: [{ name: '_agent', type: 'address' }], name: 'getAgentStreams', outputs: [{ type: 'uint256[]' }], stateMutability: 'view', type: 'function' },
  { inputs: [], name: 'nextStreamId', outputs: [{ type: 'uint256' }], stateMutability: 'view', type: 'function' },
  // Write
  { inputs: [{ name: '_agent', type: 'address' }, { name: '_agentId', type: 'bytes32' }, { name: '_token', type: 'address' }, { name: '_deposit', type: 'uint256' }, { name: '_ratePerSecond', type: 'uint256' }], name: 'createStream', outputs: [{ type: 'uint256' }], stateMutability: 'nonpayable', type: 'function' },
  { inputs: [{ name: '_streamId', type: 'uint256' }, { name: '_amount', type: 'uint256' }], name: 'topUp', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  { inputs: [{ name: '_streamId', type: 'uint256' }], name: 'pauseStream', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  { inputs: [{ name: '_streamId', type: 'uint256' }], name: 'resumeStream', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  { inputs: [{ name: '_streamId', type: 'uint256' }], name: 'cancelStream', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  { inputs: [{ name: '_streamId', type: 'uint256' }], name: 'withdraw', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  // Events
  { anonymous: false, inputs: [{ indexed: true, name: 'streamId', type: 'uint256' }, { indexed: true, name: 'sponsor', type: 'address' }, { indexed: true, name: 'agent', type: 'address' }, { indexed: false, name: 'token', type: 'address' }, { indexed: false, name: 'deposit', type: 'uint256' }, { indexed: false, name: 'ratePerSecond', type: 'uint256' }], name: 'StreamCreated', type: 'event' },
  { anonymous: false, inputs: [{ indexed: true, name: 'streamId', type: 'uint256' }, { indexed: false, name: 'amount', type: 'uint256' }], name: 'StreamWithdrawn', type: 'event' },
  { anonymous: false, inputs: [{ indexed: true, name: 'streamId', type: 'uint256' }, { indexed: false, name: 'sponsorRefund', type: 'uint256' }, { indexed: false, name: 'agentPayout', type: 'uint256' }], name: 'StreamCanceled', type: 'event' },
] as const

// ─── AgentMarketplace ─────────────────────────────────────────

export const AGENT_MARKETPLACE_ABI = [
  // Read
  { inputs: [{ name: '_agentId', type: 'bytes32' }], name: 'getListing', outputs: [{ components: [{ name: 'agentId', type: 'bytes32' }, { name: 'owner', type: 'address' }, { name: 'pricePerUnit', type: 'uint256' }, { name: 'pricingModel', type: 'uint8' }, { name: 'token', type: 'address' }, { name: 'active', type: 'bool' }, { name: 'maxConcurrent', type: 'uint256' }, { name: 'currentEngagements', type: 'uint256' }, { name: 'totalCompleted', type: 'uint256' }, { name: 'totalVolume', type: 'uint256' }, { name: 'avgRating', type: 'uint256' }, { name: 'ratingCount', type: 'uint256' }], name: '', type: 'tuple' }], stateMutability: 'view', type: 'function' },
  { inputs: [{ name: '_engagementId', type: 'uint256' }], name: 'getEngagement', outputs: [{ components: [{ name: 'engagementId', type: 'uint256' }, { name: 'agentId', type: 'bytes32' }, { name: 'hirer', type: 'address' }, { name: 'amount', type: 'uint256' }, { name: 'units', type: 'uint256' }, { name: 'startTime', type: 'uint256' }, { name: 'status', type: 'uint8' }, { name: 'rating', type: 'uint256' }], name: '', type: 'tuple' }], stateMutability: 'view', type: 'function' },
  { inputs: [{ name: '_hirer', type: 'address' }], name: 'getHirerEngagements', outputs: [{ type: 'uint256[]' }], stateMutability: 'view', type: 'function' },
  { inputs: [{ name: '_agentId', type: 'bytes32' }], name: 'getAgentEngagements', outputs: [{ type: 'uint256[]' }], stateMutability: 'view', type: 'function' },
  { inputs: [], name: 'nextEngagementId', outputs: [{ type: 'uint256' }], stateMutability: 'view', type: 'function' },
  // Write
  { inputs: [{ name: '_agentId', type: 'bytes32' }, { name: '_pricePerUnit', type: 'uint256' }, { name: '_pricingModel', type: 'uint8' }, { name: '_token', type: 'address' }, { name: '_maxConcurrent', type: 'uint256' }], name: 'listAgent', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  { inputs: [{ name: '_agentId', type: 'bytes32' }, { name: '_units', type: 'uint256' }], name: 'hireAgent', outputs: [{ type: 'uint256' }], stateMutability: 'nonpayable', type: 'function' },
  { inputs: [{ name: '_engagementId', type: 'uint256' }], name: 'completeEngagement', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  { inputs: [{ name: '_engagementId', type: 'uint256' }, { name: '_reason', type: 'string' }], name: 'disputeEngagement', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  { inputs: [{ name: '_engagementId', type: 'uint256' }], name: 'cancelEngagement', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  { inputs: [{ name: '_engagementId', type: 'uint256' }, { name: '_stars', type: 'uint256' }], name: 'rateEngagement', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  // Events
  { anonymous: false, inputs: [{ indexed: true, name: 'agentId', type: 'bytes32' }, { indexed: true, name: 'owner', type: 'address' }, { indexed: false, name: 'pricePerUnit', type: 'uint256' }, { indexed: false, name: 'pricingModel', type: 'uint8' }], name: 'AgentListed', type: 'event' },
  { anonymous: false, inputs: [{ indexed: true, name: 'engagementId', type: 'uint256' }, { indexed: true, name: 'agentId', type: 'bytes32' }, { indexed: true, name: 'hirer', type: 'address' }, { indexed: false, name: 'amount', type: 'uint256' }], name: 'AgentHired', type: 'event' },
  { anonymous: false, inputs: [{ indexed: true, name: 'engagementId', type: 'uint256' }, { indexed: false, name: 'agentPayout', type: 'uint256' }, { indexed: false, name: 'protocolFee', type: 'uint256' }], name: 'EngagementCompleted', type: 'event' },
] as const

// ─── Enum Helpers ─────────────────────────────────────────────

export const AgentStatus = { Active: 0, Paused: 1, Revoked: 2, Expired: 3 } as const
export const AgentRole = { TRADER: 0, RESEARCHER: 1, MONITOR: 2, CODER: 3, GOVERNANCE_ASSISTANT: 4, FILE_INDEXER: 5, RISK_AUDITOR: 6 } as const
export const ReputationTier = { UNTRUSTED: 0, NOVICE: 1, RELIABLE: 2, TRUSTED: 3, ELITE: 4 } as const
export const ViolationType = { RATE_LIMIT_EXCEEDED: 0, PERMISSION_VIOLATION: 1, FUND_MISUSE: 2, CRITICAL_FAULT: 3 } as const
export const PricingModel = { PerHour: 0, PerDay: 1, PerTask: 2 } as const
export const EngagementStatus = { Active: 0, Completed: 1, Disputed: 2, Canceled: 3, Resolved: 4 } as const
